export interface Cadidate {
  cadidateId : number,
  name : string,
  email : string,
  address : string,
  phone : string,
  gender : number,
  degree : string,
  university : string,
  major : string,
  applyDate : Date,
  experience : number,
  rating : number,
  providerId : string,
  categoryId : string,
  jobId : string,
  tag : string,
  dob : Date,
  skill : string
}