export interface Cadidate {
  id : number,
  dob : Date,
  name : string,
  email : string,
  address : string,
  phone : string,
  gender : number,
  degree : string,
  university : string,
  major : string,
  applydate : Date,
  experience : string,
  rating : number,
  provider : string,
  category : string,
  skill : string,
  job : string,
  tag : string
}